### DISCUSSION TITLE
CM3: Styling

### DISCUSSION THREAD

**Discussion by matheusps** [vtex/shoreline#1029] [Technical RFCs]
# Shoreline styling API

> The styling API is built using [data-attributes](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes). Make sure you understand this topic before continuing. 

Every component has its unique data-attribute for styling. It follows the pattern `data-sl-{component-name}`, where `sl` stands for Shoreline.

```jsx filename="example.jsx"
import { Button } from '@vtex/shoreline-components'
import './styles.css'

export default function App() {
  return (
    <Button>Accessible button</Button> 
  )
}
```

Adding styles to the component is simple as referencing its data-attribute.

```css filename="styles.css"
[data-sl-button] {
  cursor: pointer;
  margin: 1rem 2rem;
  /* ... */
}
```

Also, you can use classNames.

```jsx
<Button className="custom-button">Custom</Button>
```

```css
.custom-button {
  border: 1px solid red;
}
```

For library authors, it's recommended to use the [components layer](https://pvt-shoreline.vercel.app/api-reference/csx/cascade-layers#components).

```css filename="styles.css"
@layer sl-components {
  [data-sl-button] {
    cursor: pointer;
    margin: 1rem 2rem;
    /* ... */
  }
}
```

When using csx, you can reference components inside of the `components` layer using the `$` symbol: 

```ts filename="styles.css.ts"
import { csx } from '@vtex/shoreline-vanilla-extract'

export const button = csx({
  '@layer': {
    components: {
      '$button': {
        cursor: 'pointer',
        margin: '$space-2 $space-4'
      }
    }
  }
})
```

## Variants

Components often have variants. They are also represented using data-attributes. The possible values for variants are `string`, `number`, and `boolean`.  For example,

```jsx filename="example.jsx"
<Button variant="primary" /> 
```

To style this example. Reference the attribute on the CSS: 

```css filename="style.css"
@layer sl-components {
  [data-sl-button] {
    cursor: pointer;
    /* ... */
    & [data-variant="primary"] {
      background: var(--sl-color-blue-400);
    }
  }
}
```

Usage

```jsx
// application root
import "@vtex/shoreline-styles"

//... rest of the code
```

```jsx
import { Checkbox } from '@vtex/shoreline-components'
// ... 
```

or (modular)

```jsx
import { Checkbox } from 'components'
import '@vtex/shoreline-styles/checkbox' // css

```

## References

- [Ariakit](https://ariakit.org/guide/styling)
- [React Spectrum](https://react-spectrum.adobe.com/react-aria/styling.html)
- [Radix](https://www.radix-ui.com/primitives/docs/guides/styling)
