### ISSUE TITLE
Responsive props

### ISSUE THREAD

**Issue by lucasaarcoverde** [vtex/shoreline#1443]
Props responsivas

## Solução 1

Uso do componente:

```jsx
<Flex justify={{ mobile: 'center', desktop: 'start' }} />
```

Componente:
```jsx
function Flex(props) {
  const { justify } = props

  const justifyElements = getResponsiveElements('flex', justify)
  // { --sl-flex-justify-mobile: 'center', --sl-flex-justify-desktop: 'start' }

  return <div data-sl-flex style={justifyElements}>...</div>
}
```

Estilos: 
```scss
[data-sl-flex] {
  ...
  justify-content: var(--sl-justify-mobile)

  @media (min-width: 'desktop') {
    justify-content: var(--sl-justify-desktop)
  } 
}
```

Pros
* Abordagem parecida com a que a gente utiliza para tratar variantes
* Não gera nenhuma breaking change com a solução atual

Cons
* Tem que manter a mesma nomenclatura na folha de estilo e no componente

## Solução 2

Uso do componente:

```jsx
<Flex justify={{ mobile: 'center', desktop: 'start' }} />
```

Componente:

```jsx
function Flex(props) {
  const { justify } = props

  const breakpoint = useBreakpoint()
  // breakpoint = mobile | desktop | tablet | widescreen

  const justifyElement = getResponsiveElement(justify, breakpoint)
  // retorna { --sl-flex-justify: valor } com o valor sendo respectivo ao breakpoint

  return (
    <div data-sl-flex name={breakpoint} style={justifyElement}>
      ...
    </div>
  )
}
```

Estilos:

```scss
[data-sl-flex="mobile"] {
  justify-content: var(--sl-justify)
}

[data-sl-flex="desktop"] {
  @media (min-width: 'desktop') {
    justify-content: var(--sl-justify)
  } 
}
```

Pros
* Abordagem parecida com a que a gente utiliza para tratar variantes
* Não gera nenhuma breaking change com a solução atual

Cons
* Tem que manter a mesma nomenclatura na folha de estilo e no componente
* a verificação do breakpoint é feita utilizando javascript e não css puro
