### ISSUE TITLE
Inconsistent token names

### ISSUE THREAD

**Issue by matheusps** [vtex/shoreline#1530]
## Problem

The Shoreline token organization is all over the place! Let's try to implement the tertiary button: 

```css
.button-tertiary {
  background: var(--sl-bg-base-plain);
  color: var(--sl-fg-muted);
}
```

What is the relation between `bg-base-plain` and `fg-muted`? NONE!

Not convinced? Let's implement the primary button: 

```css
.button-primary {
  background: var(--sl-bg-accent-strong);
  color: var(--sl-fg-inverted);
}
```

What is the relation between `bg-accent-strong` and `fg-inverted`? NONE AS WELL! 

In summary, tokens should be easy to use. The interaction between bg, fg, and border should be clear. Right now, is not.

## Proposal

Use the same structure to represent bg, fg, and border. Also, change border to `b` to easier use. 

```css
.button-tertiary {
  background: var(--sl-bg-base-plain);
  color: var(--sl-fg-base-plain);
  border: var(--sl-b-base-plain)
}

.button-primary {
  background: var(--sl-bg-accent-strong);
  color: var(--sl-fg-accent-strong);
  border: var(--sl-b-accent-strong)
}
```

### Benefits

- Better DX (Both designer and developer), which results in a better consistency.
- Better Theming, for both creating and overriding an existing theme.
- Better Semantics.

### Tradeoffs

- The number of tokens grow.
