### ISSUE TITLE
PageHeader forces buttons to be wider

### ISSUE THREAD

**Issue by matheusps** [vtex/shoreline#1830]
### Problem

There's a global style on the page header that makes buttons larger in width. Although this is great for buttons containng text and icon+text, it makes the iconOnly buttons to look odd. 

https://github.com/user-attachments/assets/ffbedd6c-649f-4e93-9378-58995eb80d7e

### Suggested solution

Adjust the rule:

```css
[data-sl-page-header-container] :where(button) {
  min-width: 6.25rem;
}
```

to be more specific

```css
[data-sl-page-header-container] :where([data-sl-button]):not([data-sl-button-icon-only]) {
  min-width: 6.25rem;
}
```

### Package

@vtex/shoreline

### Packages version

latest

### Browser

chrome

### Package Manager

yarn
